# Generated by Django 2.0.2 on 2018-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180222_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('get_all_users_info', 'Set book as returned'),)},
        ),
    ]
